var data = [
    {num: 1, quotation:"When you know that you're capable of dealing with whatever comes, you have the only security the world has to offer.",author:'Harry Browne'},
    {num: 2, quotation:"If things start happening, don't worry, don't stew, just go right along and you'll start happening too.",author:"Dr. Seuss"},
    {num: 3, quotation:'We first make our habits, then our habits make us.',author:"John Dryden"},
    {num: 4, quotation:"It always seems impossible until it's done.",author:"Nelson Mandela"},
    {num: 5, quotation:'The best way to predict the future is to invent it.',author:"Alan Kay"},
    {num: 6, quotation:"Real knowledge is to know the extent of one's ignorance.",author:"Confucius"},
    {num: 7, quotation:"Don't watch the clock. Do what it does. Keep going.",author:"Sam Levenson"},
    {num: 8, quotation:'The scariest moment is always just before you start.',author:"Stephen King"},
    {num: 9, quotation:'Tough times never last, but tough people do.',author:"Dr. Robert Schuller"},
    {num: 10, quotation:"Today's accomplishments were yesterday's impossibilities.",author:"Robert H. Schuller"},
    {num: 11, quotation:"I've missed more than 9,000 shots during my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",author:"Michael Jordan"},
    {num: 12, quotation:'It does not matter how slowly you go as long as you do not stop.',author:"Confucius"},
    {num: 13, quotation:"If you don't risk anything, you risk even more.",author:"Erica Jong"},
    {num: 14, quotation:'The harder I work, the luckier I get.',author:"Gary Player"},
    {num: 15, quotation:'Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.',author:"Marie Curie"},
    {num: 16, quotation:'The best way out is always through.',author:"Robert Frost"},
    {num: 17, quotation:'You are never too old to set another goal, or to dream a new dream.',author:"C.S. Lewis"},
    {num: 18, quotation:'Weeks of programming can save you hours of planning.',author:"Unknown"},
    {num: 19, quotation:'Those who says it cannot be done should not interrupt the person doing it.',author:"Unknown"},
    {num: 20, quotation:'Tough times never last, but tough people do.',author:"Dr. Robert Schuller"},
    {num: 21, quotation:'Never confuse a single defeat with a final defeat.',author:"F. Scott Fitzgerald"},
    {num: 22, quotation:'Live as if you were to die tomorrow. Learn as if you were to live forever.',author:"Mahatma Gandhi"},
    {num: 23, quotation:'Life is 10% what happens to you and 90% how you react to it.',author:"Charles R. Swindoll"},
    {num: 24, quotation:'Once we accept our limits, we go beyond them.',author:"Albert Einstein"},
    {num: 25, quotation:'The only limit to our realization of tomorrow, will be our doubts of today.',author:"Franklin D. Roosevelt"},
    {num: 26, quotation:"I attribute my success to this - I never gave or took any excuse.",author:"Florence Nightingale"},
    {num: 27, quotation:'A good traveler has no fixed plans and is not intent on arriving.',author:"Lao Tzu"},
    {num: 28, quotation:'People who are crazy enough to think they can change the world, are the ones who do.',author:"Rob Siltanen"},
    {num: 29, quotation:'You only live once, but if you do it right, once is enough.',author:"Mae West"},
    {num: 30, quotation:'An ant on the move does more than a dozing ox.',author:"Lao Tzu"},
    {num: 31, quotation:'Without hard work, nothing grows but weeds.',author:"Gordon B. Hinckley"},
    {num: 32, quotation:'Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.',author:"Lao Tzu"},
    {num: 33, quotation:'In theory there is no difference between theory and practice. In practice there is.',author:"Yogi Berra"},
    {num: 34, quotation:'The most difficult thing is the decision to act. The rest is merely tenacity.',author:"Amelia Earhart"},
    {num: 35, quotation:"I have not failed. I've just found 10,000 ways that won't work.",author:"Thomas A. Edison"},
    {num: 36, quotation:'A winner is a dreamer who never gives up.',author:"Nelson Mandela"},
    {num: 37, quotation:'Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.',author:"William Shakespeare"},
    {num: 38, quotation:"Right or wrong, it's very pleasant to break something from time to time.",author:"Fyodor Dostoevsky"},
    {num: 39, quotation:"Real knowledge is to know the extent of one's ignorance.",author:"Confucius"},
    {num: 40, quotation:'The future is not laid out on a track. It is something that we can decide, and to the extent that we do not violate any known laws of the universe, we can probably make it work the way that we want to.',author:"Alan Kay"},
    {num: 41, quotation:'I dream my painting and I paint my dream.',author:"Vincent van Gogh"},
    {num: 42, quotation:'Giving up is the only sure way to fail.',author:'Gena Showalter'},
    {num: 43, quotation:'The best revenge is massive success.',author:"Frank Sinatra"},
    {num: 44, quotation:'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.',author:"Albert Einstein"},
    {num: 45, quotation:'We cannot solve our problems with the same thinking we used when we created them.',author:"Albert Einstein"},
    {num: 46, quotation:"It's not whether you get knocked down, it's whether you get up.",author:"Vince Lombardi"},
    {num: 47, quotation:"The most common way people give up their power is by thinking they don't have any.",author:"Alice Walker"},
    {num: 48, quotation:"If you reveal your secrets to the wind, you should not blame the wind for revealing them to the trees.",author:"Kahlil Gibran"},
    {num: 49, quotation:'Every strike brings me closer to the next home run.',author:"Babe Ruth"},
    {num: 50, quotation:"If you have everything under control, you're not moving fast enough.",author:"Mario Andretti"},
    {num: 51, quotation:'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.',author:"Helen Keller"},
    {num: 52, quotation:'We only see what we know.',author:"Goethe"},
    {num: 53, quotation:"Whether you think you can or think you can't, you're right.",author:"Henry Ford"},
    {num: 54, quotation:"You can't cross the sea merely by standing and staring at the water.",author:"Rabindranath Tagore"},
    {num: 55, quotation:'It is never too late to be what you might have been.',author:"Mary Anne Evans"},
    {num: 56, quotation:'The way to get started is to quit talking and begin doing.',author:"Walt Disney"},
    {num: 57, quotation:'What matters most is how well you walk through the fire.',author:"Charles Bukowski"},
    {num: 58, quotation:"If you're not making mistakes, then you're not making decisions.",author:"Catherine Cook"},
    {num: 59, quotation:'There are far, far better things ahead than any we leave behind.',author:"C.S. Lewis"},
    {num: 60, quotation:'Perseverance is failing 19 times and succeeding the 20th.',author:"Julie Andrews"},
    {num: 61, quotation:"When you know that you're capable of dealing with whatever comes, you have the only security the world has to offer.",author:"Harry Browne"},
    {num: 62, quotation:'There is no elevator to success, you have to take the stairs.',author:"Zig Ziglar"},
    {num: 63, quotation:'Make everything as simple as possible, but not simpler.',author:"Albert Einstein"},
    {num: 64, quotation:"You can, you should, and if you're brave enough to start, you will.",author:"Stephen King"},
    {num: 65, quotation:'Optimism is an occupational hazard of programming; feedback is the treatment.',author:"Kent Beck"},
    {num: 66, quotation:'The secret of getting ahead is getting started.',author:"Mark Twain"},
    {num: 67, quotation:"Impossible is just a big word thrown around by small men who find it easier to live in the world they've been given than to explore the power they have to change it. Impossible is not a fact. It's an opinion. Impossible is not a declaration. It's a dare. Impossible is potential. Impossible is temporary. Impossible is nothing.",author:"Muhammad Ali"},
    {num: 68, quotation:"There is only one corner of the universe you can be certain of improving, and that's your own self.",author:"Aldous Huxley"},
    {num: 69, quotation:'Forever is composed of nows.',author:"Emily Dickinson"},
    {num: 70, quotation:"Any code of your own that you haven't looked at for six or more months might as well have been written by someone else.",author:"Eagleson's Law"},
    {num: 71, quotation:'With the possible exception of the equator, everything begins somewhere.',author:"C.S. Lewis"},
    {num: 72, quotation:'A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.',author:"George Bernard Shaw"},
    {num: 73, quotation:'UNIX is simple. It just takes a genius to understand its simplicity.',author:"Dennis Ritchie"},
    {num: 74, quotation:'Well done is better than well said.',author:"Benjamin Franklin"},
    {num: 75, quotation:"The universe doesn't allow perfection.",author:"Stephen Hawking"},
    {num: 76, quotation:'The work of today is the history of tomorrow, and we are its makers.',author:"Juliette Gordon Low"},
    {num: 77, quotation:'We are all failures. At least the best of us are.',author:"J.M. Barrie"},
    {num: 78, quotation:'I know, somehow, that only when it is dark enough can you see the stars.',author:"Martin Luther King Jr."},
    {num: 79, quotation:"It ain't what you don't know that gets you into trouble. It's what you know for sure that just ain't so.",author:"Mark Twain"},
    {num: 80, quotation:'It is never too late to be what you might have been.',author:"Mary Anne Evans"},
    {num: 81, quotation:"It always seems impossible until it's done.",author:"Nelson Mandela"},
    {num: 82, quotation:'The price of anything is the amount of life you exchange for it.',author:"Henry David Thoreau"},
    {num: 83, quotation:'Do not wait to strike till the iron is hot; but make it hot by striking.',author:"William Butler Yeats"},
    {num: 84, quotation:'Those who says it cannot be done should not interrupt the person doing it.',author:"Unknown"},
    {num: 85, quotation:'The only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room with armed guards.',author:"Gene Spafford"},
    {num: 86, quotation:'First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack.',author:"George Carrette"},
    {num: 87, quotation:'Arise, Awake and Stop not until the goal is reached.',author:"Swami Vivekananda"},
    {num: 88, quotation:'You can see a lot by just looking.',author:"Yogi Berra"},
    {num: 89, quotation:'Quality is not an act, it is a habit.',author:"Aristotle"},
    {num: 90, quotation:'The harder the conflict, the more glorious the triumph.',author:"Thomas Paine"}]
